Scope and collection API for template.
spring-projects/spring-data-couchbase pull request #1133
Opened 2021-04-26 19:53 UTC by mikereiche

Scope and collection API for template.

Closes #963.
Original pull request: #1071.

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-04-26 22:04 UTC, mikereiche commented on src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
> +			vie = new Airport("airports::vie", "vie", "low1");
After running tests, I found some "vie", "loww" Airport records. So I made them unique to figure out what test was creating them and not deleting them.

2021-04-26 22:04 UTC, mikereiche commented on src/test/java/org/springframework/data/couchbase/util/UnmanagedTestCluster.java
> +		bucketname = "my_bucket"; // UUID.randomUUID().toString();
Reuse "my_bucket" if it already exists.  Creating the indexes, scopes and collections takes time.

2021-05-17 10:24 UTC, daschl requested changes
This change looks veeery solid already, most of  my comments are nits and small changes -- should be able to merge afterwards

2021-05-17 20:52 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
> +	public void setThreadLocalArgs(PseudoArgs pseudoArgs) {
It's never used.  Removed.

2021-05-17 20:53 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperation.java
> + * Insert Operations
fixed.

2021-05-17 20:58 UTC, mikereiche commented on pom.xml
> +            <version>3.1.0.RELEASE</version>
Updated to 3.4.6.  Seems ok.

2021-05-17 21:07 UTC, mikereiche commented on src/test/java/org/springframework/data/couchbase/util/UnmanagedTestCluster.java
> +		bucketname = "my_bucket"; // UUID.randomUUID().toString();
There are some tests that don't delete everything they've inserted.  So I will remove this change from the changeset and leave it for later when I have had time to verify that all the tests clean up after themselves.

2021-05-18 13:28 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/core/support/InScope.java
> +public interface InScope<T> {
Yes, it's not used.   Ideally, the methods in all these With* interfaces would return a parameterized interface as in the Override and implementation.  However, there is no common interface for all the different operations.  So I just define it to return Object, and T is not used.  I would like to leave the parameter there, in hopes that I eventually figure out how to define it properly.

	interface FindByQueryInScope<T> extends FindByQueryInCollection<T>, InScope<T> {
		/**
		 * With a different scope
		 *
		 * @param scope the scope to use.
		 */
		@Override
		FindByQueryInCollection<T> inScope(String scope);
	}

2021-05-26 14:06 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/core/support/WithAnalyticsConsistency.java
>  public interface WithAnalyticsConsistency<T> {
Yes, it's not used. Ideally, the methods in all these With* interfaces would return a parameterized interface as in the Override and implementation. However, there is no common interface for all the different operations. So I just define it to return Object, and T is not used. I would like to leave the parameter there, in hopes that I eventually figure out how to define it properly.

2021-05-31 17:56 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperation.java
> + * Insert Operations
fixed

2021-05-31 18:01 UTC, mikereiche commented on src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java
> +		// TODO (maybe) // method.getEntityInformation().getCollectionName(); // not yet implemented
This is irrelevant now.  This _default._default is ignored.

2021-06-01 14:41 UTC, daschl approved these changes

2021-06-02 13:38 UTC, merged