Bump couchbase sdk to 3_4_3.
spring-projects/spring-data-couchbase pull request #1663
Opened 2023-02-14 01:50 UTC by mikereiche

Requires some refactoring around @Stability.Internal APIs. Also fixed a test to get it to pass.

Closes #1661,#1662.

2023-02-14 01:51 UTC, mikereiche reviewed
@dnault  @programmatix  for review.

2023-02-14 23:29 UTC, dnault requested changes

2023-02-14 23:29 UTC, dnault commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +			} else if( query.getParameters() instanceof JsonObject && !((JsonObject)query.getParameters()).isEmpty()){
NIT: formatting

IntelliJ tip: Command-Option-Shift-L, then select "Only changes uncommitted to VCS"

2023-02-14 23:29 UTC, dnault commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +    return JsonObject.fromJson(ClassicCoreQueryOps.convertOptions(optsBuilt).toString().getBytes());
getBytes(StandardCharsets.UTF_8)

2023-02-14 23:29 UTC, dnault commented on src/test/java/org/springframework/data/couchbase/util/UnmanagedTestCluster.java
> +		bucketname = "my_bucket"; // usingCloud ? "my_bucket" : UUID.randomUUID().toString();
NIT: remove commented-out code?

2023-02-14 23:29 UTC, dnault commented on src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
> +					e.printStackTrace(); // gives IndexFailureException if the lock is still active
Does this hide other exceptions that aren't expected? (Sure, it logs the stack trace, but nobody's going to look at it if the test "passes".)

2023-02-14 23:29 UTC, dnault commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +import com.couchbase.client.core.Core;
Unused import? (not just a NIT, because Core is potentially on the chopping block)

2023-02-14 23:29 UTC, dnault commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +		}
else throw if not null?

2023-02-16 12:18 UTC, programmatix requested changes

2023-02-16 12:18 UTC, programmatix commented on src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java
> -							.queryBlocking(statement, template.getBucketName(), pArgs.getScope(), convertedOptions, false)
I forgot that Spring was using these internals directly.  Let's get these methods annotated with the new annotation so breakage like this doesn't happen again.

2023-02-16 12:18 UTC, programmatix commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +				txOptions.raw(entry.getKey(), entry.getValue());
Continue to not feel good about this approach to clone a QueryOptions into a TransactionQueryOptions...  It won't handle things like the JsonSerializer, for example.

2023-02-16 12:18 UTC, programmatix commented on src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java
> +  public static JsonObject getQueryOpts(QueryOptions.Built optsBuilt) {
It doesn't feel great turning QueryOptions into JSON, and it also calls into the internal method ClassicCoreQueryOps.convertOptions,   Luckily, I don't think this getQueryOpts is necessary anymore.  It's called from two places:

1. buildQueryOptions.  Which only uses it for getScanConsistency.  But that's not needed anymore.  QueryOptions.Built now implements CoreQueryOptions so you can call scanConsistency() directly on it.
2. buildTransactionQueryOptions.  As mentioned above I already feel a bit queasy about this solution of converting a QueryOptions into JSON and then using that to set raw parameters on a TransactionQueryOptions.  And now with CoreQueryOptions  you don't need it - you can copy over the parameters one by one (now including the serializer).

2023-02-17 21:37 UTC, dnault approved these changes

2023-02-17 22:03 UTC, merged