DATACOUCH-650 - Implements deleteById(Iterable<ID> ids).
spring-projects/spring-data-couchbase pull request #279
Opened 2020-11-13 16:46 UTC by schauder

Merge right after DATACMNS-800

2020-11-19 08:48 UTC, mp911de requested changes
There are some formatting issues. Other than that, this PR looks fine to me. Paging @daschl and @mikereiche.

2020-11-19 08:48 UTC, mp911de commented on src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
> +import com.couchbase.client.core.error.IndexExistsException;
We should verify where import changes stem from. This file seemed to be formatted properly previously.

2020-11-19 08:48 UTC, mp911de commented on src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
> +		// DATACOUCH-650
Nit: Formatting

2020-11-19 19:21 UTC, mikereiche approved these changes

2020-11-25 13:34 UTC, mp911de commented
That's merged and polished now.

2020-11-25 13:34 UTC, closed without merging